### ISSUE TITLE
large pages overview needs that sidebar menu

### ISSUE THREAD

**Issue by amchap** [EightMedia/design-manual#39]
![pages_-_freo_design_manual_-_mijn_freo_nl](https://cloud.githubusercontent.com/assets/9093958/14249875/29240edc-fa7c-11e5-9244-376d7a1cd085.png)

**Comment by Aratramba** [comment]
> The h2's will be used to create in-page-links in the sidebar navigation.

So this will work when h2's are added in the markdown file.
