### ISSUE TITLE
Header mobile

### ISSUE THREAD

**Issue by VinceFrancis** [EightMedia/design-manual#51]
![image](https://cloud.githubusercontent.com/assets/11750484/15108481/783f8a12-15d6-11e6-86e7-fa42442b15ac.png)

Zo zag het design eruit:
![image](https://cloud.githubusercontent.com/assets/11750484/15108501/8a353b9a-15d6-11e6-99de-a9786619738f.png)

* Kleinere icon pakken
* Kleiner font
* Misschien alleen design manual i.p.v. Freo design manual

**Comment by Aratramba** [comment]
> Kleinere icon pakken

ik vind zelf dat dit maakt dat je de pagina iets meer een eigen stijl kunt geven door hier een custom plaatje in te stoppen. Eigen verantwoordelijkheid dat ie blijft passen. Heb hem verborgen op mobiel.

> Kleiner font

done

> Misschien alleen design manual i.p.v. Freo design manual

is vrije content
