### ISSUE TITLE
Discussie: Hoe (js) interacties laten zien?

### ISSUE THREAD

**Issue by VinceFrancis** [EightMedia/design-manual#54]
In onze design manual kan je nu niet zien hoe bijvoorbeeld het twee staps navigatie menu bij mijn freo werkt. 
http://freo-branch-styleguide.static.eightmedia.com/styleguide/mijn-freo/components.html#header

Uiteindelijk kan je dat wel zien als je een pagina bekijkt. Zou dat genoeg zijn?

**Comment by Aratramba** [comment]
als het echt nodig is, zou een demo javascriptje genoeg moeten zijn om interacties te tonen. De mogelijkheid om js toe te voegen aan de componenten bestaat, maar dat moet uiteraard wel op maat gebouwd worden per component.
