### ISSUE TITLE
Enhancement: Viewport breedte instellen

### ISSUE THREAD

**Issue by VinceFrancis** [EightMedia/design-manual#56]
Lijkt me wel een mooie toevoeging als we hier een goede oplossing voor kunnen bedenken.

Voorbeelden: 
![image](https://cloud.githubusercontent.com/assets/11750484/15110265/2bbe25ea-15e0-11e6-8f49-6d719846334b.png)
http://styleguide.devbproto.com/styleguide/#4

![image](https://cloud.githubusercontent.com/assets/11750484/15110316/5ed7e934-15e0-11e6-85f6-7b91c11af895.png)
http://demo.patternlab.io/

**Comment by Aratramba** [comment]
https://material.io/resizer/#device=window&width=1280

![screen shot 2017-04-10 at 07 45 57](https://cloud.githubusercontent.com/assets/580312/24847538/d00bbf6a-1dc1-11e7-9936-da79bfe1b08f.png)
